Repository react-sprint/programming-tutor, pull requests merged in 2021-02, with the labels that each got.

#1 Env/initial scaffolding
  .eslintrc.js
  .gitignore
  babel.config.js
  configs/webpack/webpack.config.base.js
  configs/webpack/webpack.config.dev.js
  configs/webpack/webpack.config.prod.js
  linit-staged.config.js
  package.json
  prettier.config.js
  public/index.html
  src/components/App.tsx
  src/index.tsx
  tsconfig.json
  yarn.lock
Labels: Please Review :bow:

#2 env: set pr convention
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Please Review :bow:

#4 feat: Add ci to test react app build
  .DS_Store
  .github/workflows/ci.yml
  .gitignore
  src/.DS_Store
Labels: enhancement

#6 env: set scss, postcss, classnames
  @types/scss.d.ts
  configs/webpack/webpack.config.base.js
  package-lock.json
  package.json
  src/components/counter/index.scss
  src/components/counter/index.tsx
  src/modules/example/counter.ts
  tsconfig.json
  yarn.lock
Labels: Enhancement 👋, Please Review :bow:
